from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass
class AeoScoreBreakdown:
    overall_score: int
    score_label: str
    mention_score: int
    citation_score: int
    position_score: int
    coverage_score: int
    average_position: Optional[float]
    weights: Dict[str, float]
    formula: str


class VisibilityScorerEngine:
    """
    Deterministic AEO Visibility Scoring Engine.
    Computes an explainable, normalized 0-100 score based on Mention Rate, Citation Share,
    Position Rank, and Question Coverage.
    """

    WEIGHT_MENTION = 0.35
    WEIGHT_CITATION = 0.25
    WEIGHT_POSITION = 0.20
    WEIGHT_COVERAGE = 0.20

    @classmethod
    def get_score_label(cls, score: int) -> str:
        if score >= 90:
            return "Excellent"
        elif score >= 75:
            return "Good"
        elif score >= 50:
            return "Needs Improvement"
        elif score >= 25:
            return "Poor"
        else:
            return "Critical"

    @classmethod
    def calculate_visibility_score(
        cls,
        total_questions: int,
        questions_answered: int,
        brand_mentions_count: int,
        total_answers_count: int,
        own_citations_count: int,
        total_citations_count: int,
        detected_positions: List[int],
    ) -> AeoScoreBreakdown:
        """
        Computes the complete explainable AEO Visibility Score breakdown.
        """
        # 1. Mention Score (0-100)
        if total_answers_count > 0:
            mention_rate = (brand_mentions_count / total_answers_count) * 100.0
        else:
            mention_rate = 0.0
        mention_score = int(round(min(max(mention_rate, 0.0), 100.0)))

        # 2. Citation Score (0-100)
        if total_citations_count > 0:
            citation_rate = (own_citations_count / total_citations_count) * 100.0
        else:
            # If no citations were generated by any engine, citation score is baseline 0
            citation_rate = 0.0
        citation_score = int(round(min(max(citation_rate, 0.0), 100.0)))

        # 3. Position Score (0-100)
        avg_pos = None
        if detected_positions:
            avg_pos = round(sum(detected_positions) / len(detected_positions), 2)
            # Position 1 -> 100, Position 2 -> 80, Position 3 -> 65, Position 4 -> 50, Pos 5+ -> 30
            pos_score_raw = max(100.0 - (avg_pos - 1.0) * 20.0, 20.0)
        else:
            # If brand was never mentioned in a ranked list
            pos_score_raw = 50.0 if brand_mentions_count > 0 else 0.0
        position_score = int(round(min(max(pos_score_raw, 0.0), 100.0)))

        # 4. Coverage Score (0-100)
        if total_questions > 0:
            cov_rate = (questions_answered / total_questions) * 100.0
        else:
            cov_rate = 0.0
        coverage_score = int(round(min(max(cov_rate, 0.0), 100.0)))

        # Weighted composite score
        overall_raw = (
            (cls.WEIGHT_MENTION * mention_score)
            + (cls.WEIGHT_CITATION * citation_score)
            + (cls.WEIGHT_POSITION * position_score)
            + (cls.WEIGHT_COVERAGE * coverage_score)
        )
        overall_score = int(round(min(max(overall_raw, 0.0), 100.0)))

        return AeoScoreBreakdown(
            overall_score=overall_score,
            score_label=cls.get_score_label(overall_score),
            mention_score=mention_score,
            citation_score=citation_score,
            position_score=position_score,
            coverage_score=coverage_score,
            average_position=avg_pos,
            weights={
                "mention": cls.WEIGHT_MENTION,
                "citation": cls.WEIGHT_CITATION,
                "position": cls.WEIGHT_POSITION,
                "coverage": cls.WEIGHT_COVERAGE,
            },
            formula="0.35 * Mention + 0.25 * Citation + 0.20 * Position + 0.20 * Coverage",
        )
