from __future__ import annotations
import hashlib
import hmac
import json
import uuid
import logging
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, Optional, Tuple
import httpx
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.billing import (
    Plan,
    PlanCode,
    Subscription,
    SubscriptionStatus,
    BillingCustomer,
    CreditWallet,
    CreditPurchase,
    Payment,
    PaymentStatus,
    Invoice,
    BillingWebhookEvent,
    CreditTransactionType,
)
from app.models.base import utc_now
from app.services.credit_service import (
    PlanService,
    CreditWalletService,
    CreditAllocationService,
)
from app.core.config import settings

logger = logging.getLogger(__name__)

# One-time Credit Packages (Exact Match to Specification)
ONE_TIME_CREDIT_PACKS: Dict[int, Dict[str, Any]] = {
    250: {"credits": 250, "price": 2.99, "name": "250 Extra Credits Pack", "description": "Quick top-up for a small crawl or audit run"},
    500: {"credits": 500, "price": 4.49, "name": "500 Extra Credits Pack", "description": "Ideal for deeper site crawl or prompt exploration"},
    1000: {"credits": 1000, "price": 7.99, "name": "1,000 Extra Credits Pack", "description": "Most popular top-up for multi-engine comparisons"},
    2500: {"credits": 2500, "price": 17.99, "name": "2,500 Extra Credits Pack", "description": "Best for high-volume audit sweeps and batch queries"},
    5000: {"credits": 5000, "price": 29.99, "name": "5,000 Extra Credits Pack", "description": "Maximum value pack for agency workloads"},
}


class RazorpayService:
    """Production-grade Razorpay payment gateway, orders, signature verification, and webhook engine."""

    @staticmethod
    def is_configured() -> bool:
        """Returns True if real Razorpay API keys are configured in environment."""
        return bool(
            settings.RAZORPAY_KEY_ID
            and settings.RAZORPAY_KEY_SECRET
            and settings.RAZORPAY_KEY_ID.startswith("rzp_")
        )

    @staticmethod
    def get_public_key() -> str:
        """Returns public Key ID to pass to frontend Razorpay checkout modal."""
        return settings.RAZORPAY_KEY_ID or "rzp_test_placeholder"

    @staticmethod
    def get_currency() -> str:
        """Returns active billing currency."""
        return (settings.RAZORPAY_CURRENCY or "USD").upper()

    @staticmethod
    def verify_signature(order_id: str, payment_id: str, signature: str) -> bool:
        """Verifies HMAC-SHA256 signature generated by Razorpay Checkout."""
        if not settings.RAZORPAY_KEY_SECRET:
            # In local sandbox/test mode without keys, allow test signatures
            if signature.startswith("test_sig_") or order_id.startswith("order_test_"):
                return True
            return False

        generated_signature = hmac.new(
            settings.RAZORPAY_KEY_SECRET.encode("utf-8"),
            f"{order_id}|{payment_id}".encode("utf-8"),
            hashlib.sha256,
        ).hexdigest()

        return hmac.compare_digest(generated_signature, signature)

    @staticmethod
    def verify_webhook_signature(raw_body: bytes, signature: str) -> bool:
        """Verifies Razorpay webhook signature header against body."""
        secret = settings.RAZORPAY_WEBHOOK_SECRET or settings.RAZORPAY_KEY_SECRET
        if not secret:
            return False

        expected_signature = hmac.new(
            secret.encode("utf-8"),
            raw_body,
            hashlib.sha256,
        ).hexdigest()

        return hmac.compare_digest(expected_signature, signature)

    @staticmethod
    async def create_plan_order(
        db: AsyncSession,
        workspace_id: str,
        plan_code: str,
        user_email: str,
        billing_cycle: str = "monthly",
        user_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Creates a Razorpay Order for a recurring plan upgrade."""
        plan = await PlanService.get_plan_by_code(db, plan_code)
        if not plan:
            raise ValueError(f"Invalid plan code: {plan_code}")

        if plan.code == PlanCode.FREE.value:
            # Free plan activates immediately
            await RazorpayService.activate_free_plan(db, workspace_id, user_id)
            return {
                "order_id": f"order_free_{uuid.uuid4().hex[:10]}",
                "amount": 0,
                "currency": RazorpayService.get_currency(),
                "key_id": RazorpayService.get_public_key(),
                "plan_code": PlanCode.FREE.value,
                "is_free": True,
                "message": "Free plan activated successfully.",
            }

        # Calculate price based on billing cycle (20% discount on annual)
        price = plan.price_monthly
        if billing_cycle == "annual":
            price = round(plan.price_monthly * 0.8 * 12, 2)

        # Amount in smallest currency unit (e.g. cents for USD, paise for INR)
        amount_in_subunits = int(round(price * 100))
        currency = RazorpayService.get_currency()
        receipt_id = f"rcpt_plan_{uuid.uuid4().hex[:10]}"

        order_id = f"order_test_{uuid.uuid4().hex[:12]}"

        # Call live Razorpay API if configured
        if RazorpayService.is_configured():
            try:
                auth = (settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET)
                payload = {
                    "amount": amount_in_subunits,
                    "currency": currency,
                    "receipt": receipt_id,
                    "notes": {
                        "workspace_id": workspace_id,
                        "user_id": user_id or "",
                        "plan_code": plan.code,
                        "billing_cycle": billing_cycle,
                        "user_email": user_email,
                        "type": "subscription_upgrade",
                    },
                }
                async with httpx.AsyncClient(timeout=20.0) as client:
                    resp = await client.post(
                        "https://api.razorpay.com/v1/orders",
                        json=payload,
                        auth=auth,
                    )
                    if resp.status_code in (200, 201):
                        order_data = resp.json()
                        order_id = order_data.get("id", order_id)
                    else:
                        logger.error("Razorpay order creation failed: %s %s", resp.status_code, resp.text)
                        raise ValueError(f"Razorpay error: {resp.text}")
            except Exception as e:
                logger.error("Error connecting to Razorpay API: %s", e)
                if not order_id.startswith("order_test_"):
                    raise

        # Record pending payment in database
        payment = Payment(
            id=str(uuid.uuid4()),
            workspace_id=workspace_id,
            user_id=user_id,
            provider="razorpay",
            provider_payment_id=order_id,
            amount=price,
            currency=currency,
            status=PaymentStatus.PENDING.value,
            payment_type="subscription",
            payment_metadata={
                "order_id": order_id,
                "plan_code": plan.code,
                "billing_cycle": billing_cycle,
                "user_email": user_email,
            },
        )
        db.add(payment)
        await db.commit()

        return {
            "order_id": order_id,
            "amount": amount_in_subunits,
            "amount_display": price,
            "currency": currency,
            "key_id": RazorpayService.get_public_key(),
            "plan_code": plan.code,
            "plan_name": plan.name,
            "billing_cycle": billing_cycle,
            "user_email": user_email,
            "is_free": False,
            "name": "SEOSensing",
            "description": f"{plan.name} Plan ({billing_cycle.capitalize()}) - {plan.monthly_credits:,} credits/mo",
        }

    @staticmethod
    async def create_credit_pack_order(
        db: AsyncSession,
        workspace_id: str,
        pack_credits: int,
        user_email: str,
        user_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Creates a Razorpay Order for a one-time credit top-up pack."""
        pack = ONE_TIME_CREDIT_PACKS.get(pack_credits)
        if not pack:
            raise ValueError(f"Invalid credit pack size: {pack_credits}. Choose from 250, 500, 1000, 2500, 5000.")

        price = pack["price"]
        amount_in_subunits = int(round(price * 100))
        currency = RazorpayService.get_currency()
        receipt_id = f"rcpt_pack_{uuid.uuid4().hex[:10]}"

        order_id = f"order_test_{uuid.uuid4().hex[:12]}"

        # Call live Razorpay API if configured
        if RazorpayService.is_configured():
            try:
                auth = (settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET)
                payload = {
                    "amount": amount_in_subunits,
                    "currency": currency,
                    "receipt": receipt_id,
                    "notes": {
                        "workspace_id": workspace_id,
                        "user_id": user_id or "",
                        "pack_credits": str(pack_credits),
                        "user_email": user_email,
                        "type": "credit_topup",
                    },
                }
                async with httpx.AsyncClient(timeout=20.0) as client:
                    resp = await client.post(
                        "https://api.razorpay.com/v1/orders",
                        json=payload,
                        auth=auth,
                    )
                    if resp.status_code in (200, 201):
                        order_data = resp.json()
                        order_id = order_data.get("id", order_id)
                    else:
                        logger.error("Razorpay credit pack order creation failed: %s %s", resp.status_code, resp.text)
                        raise ValueError(f"Razorpay error: {resp.text}")
            except Exception as e:
                logger.error("Error connecting to Razorpay API: %s", e)
                if not order_id.startswith("order_test_"):
                    raise

        # Record pending payment
        payment = Payment(
            id=str(uuid.uuid4()),
            workspace_id=workspace_id,
            user_id=user_id,
            provider="razorpay",
            provider_payment_id=order_id,
            amount=price,
            currency=currency,
            status=PaymentStatus.PENDING.value,
            payment_type="credit_topup",
            payment_metadata={
                "order_id": order_id,
                "pack_credits": pack_credits,
                "user_email": user_email,
            },
        )
        db.add(payment)
        await db.commit()

        return {
            "order_id": order_id,
            "amount": amount_in_subunits,
            "amount_display": price,
            "currency": currency,
            "key_id": RazorpayService.get_public_key(),
            "pack_credits": pack_credits,
            "user_email": user_email,
            "name": "SEOSensing",
            "description": f"{pack['name']} ({pack_credits:,} Top-Up Credits)",
        }

    @staticmethod
    async def verify_and_fulfill_payment(
        db: AsyncSession,
        workspace_id: str,
        razorpay_order_id: str,
        razorpay_payment_id: str,
        razorpay_signature: str,
        user_id: Optional[str] = None,
        plan_code: Optional[str] = None,
        pack_credits: Optional[int] = None,
        billing_cycle: str = "monthly",
    ) -> Dict[str, Any]:
        """Verifies signature and immediately activates subscription or credits wallet."""
        is_valid = RazorpayService.verify_signature(
            order_id=razorpay_order_id,
            payment_id=razorpay_payment_id,
            signature=razorpay_signature,
        )

        if not is_valid:
            logger.warning("Invalid Razorpay payment signature for order %s", razorpay_order_id)
            raise ValueError("Invalid payment signature. Payment verification failed.")

        # Check for existing payment record or create
        stmt = select(Payment).where(Payment.provider_payment_id == razorpay_order_id)
        res = await db.execute(stmt)
        payment = res.scalar_one_or_none()

        now = utc_now()

        if payment:
            payment.status = PaymentStatus.SUCCEEDED.value
            payment.payment_metadata = {
                **(payment.payment_metadata or {}),
                "razorpay_payment_id": razorpay_payment_id,
                "razorpay_signature": razorpay_signature,
                "verified_at": now.isoformat(),
            }
        else:
            payment = Payment(
                id=str(uuid.uuid4()),
                workspace_id=workspace_id,
                user_id=user_id,
                provider="razorpay",
                provider_payment_id=razorpay_payment_id,
                amount=0.0,
                currency=RazorpayService.get_currency(),
                status=PaymentStatus.SUCCEEDED.value,
                payment_type="subscription" if plan_code else "credit_topup",
                payment_metadata={
                    "razorpay_order_id": razorpay_order_id,
                    "razorpay_payment_id": razorpay_payment_id,
                    "razorpay_signature": razorpay_signature,
                },
            )
            db.add(payment)

        # Fulfill Subscription Upgrade
        if plan_code and plan_code != PlanCode.FREE.value:
            plan = await PlanService.get_plan_by_code(db, plan_code)
            if not plan:
                raise ValueError(f"Plan not found: {plan_code}")

            period_start = now
            period_end = now + timedelta(days=365 if billing_cycle == "annual" else 30)

            # Update or create active Subscription
            sub_stmt = select(Subscription).where(Subscription.workspace_id == workspace_id)
            sub_res = await db.execute(sub_stmt)
            sub = sub_res.scalar_one_or_none()

            if sub:
                sub.plan_id = plan.id
                sub.provider = "razorpay"
                sub.provider_subscription_id = razorpay_order_id
                sub.status = SubscriptionStatus.ACTIVE.value
                sub.billing_interval = billing_cycle
                sub.current_period_start = period_start
                sub.current_period_end = period_end
                sub.cancel_at_period_end = False
            else:
                sub = Subscription(
                    id=str(uuid.uuid4()),
                    workspace_id=workspace_id,
                    plan_id=plan.id,
                    provider="razorpay",
                    provider_subscription_id=razorpay_order_id,
                    status=SubscriptionStatus.ACTIVE.value,
                    billing_interval=billing_cycle,
                    current_period_start=period_start,
                    current_period_end=period_end,
                    cancel_at_period_end=False,
                )
                db.add(sub)

            # Allocate monthly credits + apply rollover
            await CreditAllocationService.allocate_subscription_period(
                db=db,
                workspace_id=workspace_id,
                plan=plan,
                period_start=period_start,
                period_end=period_end,
                user_id=user_id,
            )

            # Create Invoice record
            invoice_num = f"INV-RZP-{razorpay_payment_id[-8:].upper()}"
            invoice = Invoice(
                id=str(uuid.uuid4()),
                workspace_id=workspace_id,
                user_id=user_id,
                provider_invoice_id=razorpay_payment_id,
                invoice_number=invoice_num,
                amount=payment.amount if payment.amount > 0 else plan.price_monthly,
                currency=RazorpayService.get_currency(),
                status="paid",
                period_start=period_start,
                period_end=period_end,
            )
            db.add(invoice)

            await db.commit()
            wallet = await CreditWalletService.get_or_create_wallet(db, workspace_id, user_id)

            return {
                "success": True,
                "verified": True,
                "type": "subscription",
                "plan_code": plan.code,
                "plan_name": plan.name,
                "message": f"Successfully upgraded to {plan.name} Plan! Your wallet has been credited.",
                "available_credits": wallet.available_credits,
                "invoice_number": invoice_num,
            }

        # Fulfill One-Time Credit Pack Purchase
        elif pack_credits:
            pack = ONE_TIME_CREDIT_PACKS.get(pack_credits)
            if not pack:
                raise ValueError(f"Invalid credit pack size: {pack_credits}")

            tx = await CreditWalletService.add_credits_atomic(
                db=db,
                workspace_id=workspace_id,
                amount=pack_credits,
                type=CreditTransactionType.PURCHASE.value,
                operation="razorpay_credit_purchase",
                description=f"Razorpay Purchase: {pack['name']} (+{pack_credits:,} credits)",
                user_id=user_id,
                metadata={
                    "razorpay_order_id": razorpay_order_id,
                    "razorpay_payment_id": razorpay_payment_id,
                    "price_paid": pack["price"],
                },
                idempotency_key=f"rzp_tx_{razorpay_payment_id}",
            )

            # Record purchase
            purchase = CreditPurchase(
                id=str(uuid.uuid4()),
                workspace_id=workspace_id,
                user_id=user_id,
                credits_amount=pack_credits,
                price_paid=pack["price"],
                currency=RazorpayService.get_currency(),
                provider_payment_id=razorpay_payment_id,
                status=PaymentStatus.SUCCEEDED.value,
            )
            db.add(purchase)

            # Create Invoice
            invoice_num = f"INV-RZP-{razorpay_payment_id[-8:].upper()}"
            invoice = Invoice(
                id=str(uuid.uuid4()),
                workspace_id=workspace_id,
                user_id=user_id,
                provider_invoice_id=razorpay_payment_id,
                invoice_number=invoice_num,
                amount=pack["price"],
                currency=RazorpayService.get_currency(),
                status="paid",
            )
            db.add(invoice)

            await db.commit()
            wallet = await CreditWalletService.get_or_create_wallet(db, workspace_id, user_id)

            return {
                "success": True,
                "verified": True,
                "type": "credit_topup",
                "pack_credits": pack_credits,
                "message": f"Successfully purchased {pack_credits:,} credits! Credits are now available in your wallet.",
                "available_credits": wallet.available_credits,
                "invoice_number": invoice_num,
            }

        await db.commit()
        wallet = await CreditWalletService.get_or_create_wallet(db, workspace_id, user_id)

        return {
            "success": True,
            "message": "Payment verified successfully.",
            "available_credits": wallet.available_credits,
        }

    @staticmethod
    async def activate_free_plan(
        db: AsyncSession, workspace_id: str, user_id: Optional[str] = None
    ) -> bool:
        """Activates default Free plan (50 credits/mo)."""
        free_plan = await PlanService.get_plan_by_code(db, PlanCode.FREE.value)
        if not free_plan:
            plans = await PlanService.ensure_seed_plans(db)
            free_plan = next(p for p in plans if p.code == PlanCode.FREE.value)

        now = utc_now()
        stmt = select(Subscription).where(Subscription.workspace_id == workspace_id)
        res = await db.execute(stmt)
        sub = res.scalar_one_or_none()

        if sub:
            sub.plan_id = free_plan.id
            sub.provider = "razorpay"
            sub.status = SubscriptionStatus.ACTIVE.value
            sub.current_period_start = now
            sub.current_period_end = now + timedelta(days=30)
        else:
            sub = Subscription(
                id=str(uuid.uuid4()),
                workspace_id=workspace_id,
                plan_id=free_plan.id,
                provider="razorpay",
                status=SubscriptionStatus.ACTIVE.value,
                billing_interval="monthly",
                current_period_start=now,
                current_period_end=now + timedelta(days=30),
            )
            db.add(sub)

        # Initialize or update wallet
        wallet = await CreditWalletService.get_or_create_wallet(db, workspace_id, user_id)
        wallet.monthly_credits = free_plan.monthly_credits
        wallet.available_credits = max(wallet.available_credits, free_plan.monthly_credits)

        await db.commit()
        return True

    @staticmethod
    async def process_webhook_event(
        db: AsyncSession, event_payload: Dict[str, Any], raw_body: bytes, signature: str
    ) -> Dict[str, Any]:
        """Processes server-to-server Razorpay webhooks idempotently."""
        event_id = event_payload.get("event_id") or event_payload.get("id") or str(uuid.uuid4())
        event_type = event_payload.get("event", "unknown")

        # Idempotency check
        stmt = select(BillingWebhookEvent).where(BillingWebhookEvent.event_id == event_id)
        res = await db.execute(stmt)
        if res.scalar_one_or_none():
            return {"status": "already_processed", "event_id": event_id}

        # Verify signature if webhook secret is configured
        if settings.RAZORPAY_WEBHOOK_SECRET:
            if not RazorpayService.verify_webhook_signature(raw_body, signature):
                logger.warning("Invalid Razorpay webhook signature for event %s", event_id)
                raise ValueError("Invalid webhook signature")

        webhook_event = BillingWebhookEvent(
            id=str(uuid.uuid4()),
            event_id=event_id,
            provider="razorpay",
            event_type=event_type,
            raw_payload=event_payload,
            status="processing",
        )
        db.add(webhook_event)
        await db.commit()

        try:
            payload_data = event_payload.get("payload", {})

            # Handle payment.captured / order.paid
            if event_type in ("order.paid", "payment.captured"):
                payment_entity = payload_data.get("payment", {}).get("entity", {})
                notes = payment_entity.get("notes", {})
                workspace_id = notes.get("workspace_id")
                plan_code = notes.get("plan_code")
                pack_credits_str = notes.get("pack_credits")
                order_id = payment_entity.get("order_id", "")
                payment_id = payment_entity.get("id", "")

                if workspace_id:
                    pack_credits = int(pack_credits_str) if pack_credits_str else None
                    await RazorpayService.verify_and_fulfill_payment(
                        db=db,
                        workspace_id=workspace_id,
                        razorpay_order_id=order_id,
                        razorpay_payment_id=payment_id,
                        razorpay_signature="webhook_verified",
                        plan_code=plan_code,
                        pack_credits=pack_credits,
                        billing_cycle=notes.get("billing_cycle", "monthly"),
                    )

            webhook_event.status = "processed"
            webhook_event.processed_at = utc_now()
            await db.commit()
            return {"status": "success", "event_type": event_type}

        except Exception as e:
            logger.error("Error processing Razorpay webhook event %s: %s", event_id, e)
            webhook_event.status = "failed"
            webhook_event.error_message = str(e)
            await db.commit()
            raise
