"""initial dev baseline

Revision ID: ff4b224fc22c
Revises: 
Create Date: 2026-09-28 17:05:38.903001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4b224fc22c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('monthly_credits', sa.Integer(), nullable=False),
    sa.Column('max_rollover_credits', sa.Integer(), nullable=False),
    sa.Column('max_projects', sa.Integer(), nullable=False),
    sa.Column('max_websites', sa.Integer(), nullable=False),
    sa.Column('max_team_members', sa.Integer(), nullable=False),
    sa.Column('max_ai_queries', sa.Integer(), nullable=False),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('advanced_monitoring', sa.Boolean(), nullable=False),
    sa.Column('competitor_monitoring', sa.Boolean(), nullable=False),
    sa.Column('pdf_reports', sa.Boolean(), nullable=False),
    sa.Column('api_access', sa.Boolean(), nullable=False),
    sa.Column('white_label', sa.Boolean(), nullable=False),
    sa.Column('priority_processing', sa.Boolean(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('stripe_product_id', sa.String(length=128), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_plans_code'), 'billing_plans', ['code'], unique=True)
    op.create_table('billing_webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_webhook_events_event_id'), 'billing_webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_billing_webhook_events_event_type'), 'billing_webhook_events', ['event_type'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_email'), 'password_resets', ['email'], unique=False)
    op.create_table('platform_integrations',
    sa.Column('id', sa.String(length=50), nullable=False, comment='Provider identifier (e.g. gsc, ga4, ahrefs, semrush, openai, perplexity, gemini, copilot)'),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='SEO, AEO, or Analytics'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='connected, disconnected, error, syncing'),
    sa.Column('auth_type', sa.String(length=30), nullable=False, comment='api_key, oauth, service_account'),
    sa.Column('credentials_masked', sa.String(length=255), nullable=True, comment='Masked API key or token for UI display (e.g. sk-live-...78f2)'),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True, comment='Securely stored credential or token'),
    sa.Column('config', sa.JSON(), nullable=False, comment='Provider specific settings like model name, property ID, domain, etc.'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=30), nullable=False, comment='idle, success, failed, in_progress'),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('telemetry_data', sa.JSON(), nullable=False, comment='Real-time telemetry payload cached from provider'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_integrations_provider'), 'platform_integrations', ['provider'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=50), nullable=False, comment='Settings scope identifier (e.g. global)'),
    sa.Column('workspace_name', sa.String(length=255), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('default_language', sa.String(length=50), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=False),
    sa.Column('default_crawler_policy', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('aeo_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('brand_aliases', sa.JSON(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('target_language', sa.String(length=20), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('aeo_score', sa.Integer(), nullable=True),
    sa.Column('score_label', sa.String(length=50), nullable=True),
    sa.Column('mention_score', sa.Integer(), nullable=True),
    sa.Column('citation_score', sa.Integer(), nullable=True),
    sa.Column('position_score', sa.Integer(), nullable=True),
    sa.Column('coverage_score', sa.Integer(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_projects_domain'), 'aeo_projects', ['domain'], unique=False)
    op.create_index(op.f('ix_aeo_projects_user_id'), 'aeo_projects', ['user_id'], unique=False)
    op.create_table('billing_credit_purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('credits_amount', sa.Integer(), nullable=False),
    sa.Column('price_paid', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_credit_purchases_provider_payment_id'), 'billing_credit_purchases', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_billing_credit_purchases_user_id'), 'billing_credit_purchases', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_credit_purchases_workspace_id'), 'billing_credit_purchases', ['workspace_id'], unique=False)
    op.create_table('billing_credit_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('transaction_metadata', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_credit_transactions_idempotency_key'), 'billing_credit_transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_billing_credit_transactions_type'), 'billing_credit_transactions', ['type'], unique=False)
    op.create_index(op.f('ix_billing_credit_transactions_user_id'), 'billing_credit_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_credit_transactions_workspace_id'), 'billing_credit_transactions', ['workspace_id'], unique=False)
    op.create_table('billing_credit_wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('available_credits', sa.Integer(), nullable=False),
    sa.Column('monthly_credits', sa.Integer(), nullable=False),
    sa.Column('rollover_credits', sa.Integer(), nullable=False),
    sa.Column('purchased_credits', sa.Integer(), nullable=False),
    sa.Column('used_credits', sa.Integer(), nullable=False),
    sa.Column('reserved_credits', sa.Integer(), nullable=False),
    sa.Column('last_allocation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_allocation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_credit_wallets_user_id'), 'billing_credit_wallets', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_credit_wallets_workspace_id'), 'billing_credit_wallets', ['workspace_id'], unique=True)
    op.create_table('billing_customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_customers_provider_customer_id'), 'billing_customers', ['provider_customer_id'], unique=True)
    op.create_index(op.f('ix_billing_customers_user_id'), 'billing_customers', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_customers_workspace_id'), 'billing_customers', ['workspace_id'], unique=False)
    op.create_table('billing_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('provider_checkout_session_id', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_payments_provider_checkout_session_id'), 'billing_payments', ['provider_checkout_session_id'], unique=False)
    op.create_index(op.f('ix_billing_payments_provider_payment_id'), 'billing_payments', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_billing_payments_user_id'), 'billing_payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_payments_workspace_id'), 'billing_payments', ['workspace_id'], unique=False)
    op.create_table('billing_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=128), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('billing_interval', sa.String(length=16), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_subscriptions_provider_customer_id'), 'billing_subscriptions', ['provider_customer_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_provider_subscription_id'), 'billing_subscriptions', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_user_id'), 'billing_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_workspace_id'), 'billing_subscriptions', ['workspace_id'], unique=True)
    op.create_table('billing_usage_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_model', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('usage_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_usage_events_module'), 'billing_usage_events', ['module'], unique=False)
    op.create_index(op.f('ix_billing_usage_events_user_id'), 'billing_usage_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_usage_events_workspace_id'), 'billing_usage_events', ['workspace_id'], unique=False)
    op.create_table('geo_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('brand_aliases', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sub_industry', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('target_locations', sa.JSON(), nullable=False),
    sa.Column('target_languages', sa.JSON(), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('primary_topics', sa.JSON(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('social_profiles', sa.JSON(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('geo_score', sa.Integer(), nullable=True),
    sa.Column('visibility_score', sa.Integer(), nullable=True),
    sa.Column('mention_score', sa.Integer(), nullable=True),
    sa.Column('recommendation_score', sa.Integer(), nullable=True),
    sa.Column('entity_score', sa.Integer(), nullable=True),
    sa.Column('citation_score', sa.Integer(), nullable=True),
    sa.Column('content_score', sa.Integer(), nullable=True),
    sa.Column('authority_score', sa.Integer(), nullable=True),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('consistency_score', sa.Integer(), nullable=True),
    sa.Column('score_label', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('data_coverage', sa.Integer(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_projects_domain'), 'geo_projects', ['domain'], unique=False)
    op.create_index(op.f('ix_geo_projects_user_id'), 'geo_projects', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_domain'), 'projects', ['domain'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('aeo_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('engines_analyzed', sa.JSON(), nullable=False),
    sa.Column('questions_analyzed_count', sa.Integer(), nullable=False),
    sa.Column('answers_collected_count', sa.Integer(), nullable=False),
    sa.Column('mentions_found_count', sa.Integer(), nullable=False),
    sa.Column('citations_found_count', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('summary_data', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_analyses_project_id'), 'aeo_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_aeo_analyses_status'), 'aeo_analyses', ['status'], unique=False)
    op.create_table('aeo_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('mentions_count', sa.Integer(), nullable=False),
    sa.Column('visibility_rate', sa.Integer(), nullable=False),
    sa.Column('associated_concepts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_entities_entity_name'), 'aeo_entities', ['entity_name'], unique=False)
    op.create_index(op.f('ix_aeo_entities_project_id'), 'aeo_entities', ['project_id'], unique=False)
    op.create_table('aeo_monitoring_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('selected_engines', sa.JSON(), nullable=False),
    sa.Column('alert_thresholds', sa.JSON(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_monitoring_schedules_project_id'), 'aeo_monitoring_schedules', ['project_id'], unique=True)
    op.create_table('aeo_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.String(length=1024), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('is_tracked', sa.Boolean(), nullable=False),
    sa.Column('visibility_status', sa.String(length=50), nullable=False),
    sa.Column('visibility_score', sa.Integer(), nullable=True),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=False),
    sa.Column('best_rank_position', sa.Integer(), nullable=True),
    sa.Column('trend_change', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_questions_category'), 'aeo_questions', ['category'], unique=False)
    op.create_index(op.f('ix_aeo_questions_project_id'), 'aeo_questions', ['project_id'], unique=False)
    op.create_index(op.f('ix_aeo_questions_question_text'), 'aeo_questions', ['question_text'], unique=False)
    op.create_table('aeo_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_code', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('priority_level', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('opportunity_score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('current_state', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('how_to_fix', sa.Text(), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=False),
    sa.Column('estimated_impact', sa.Integer(), nullable=False),
    sa.Column('current_score', sa.Integer(), nullable=True),
    sa.Column('potential_score', sa.Integer(), nullable=True),
    sa.Column('affected_prompt_count', sa.Integer(), nullable=False),
    sa.Column('affected_answer_count', sa.Integer(), nullable=False),
    sa.Column('affected_urls', sa.JSON(), nullable=False),
    sa.Column('implementation_steps', sa.JSON(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_recommendations_project_id'), 'aeo_recommendations', ['project_id'], unique=False)
    op.create_index(op.f('ix_aeo_recommendations_recommendation_code'), 'aeo_recommendations', ['recommendation_code'], unique=False)
    op.create_table('aeo_visibility_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('score_label', sa.String(length=50), nullable=False),
    sa.Column('mention_score', sa.Integer(), nullable=False),
    sa.Column('citation_score', sa.Integer(), nullable=False),
    sa.Column('position_score', sa.Integer(), nullable=False),
    sa.Column('coverage_score', sa.Integer(), nullable=False),
    sa.Column('average_position', sa.Float(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('questions_mentioned', sa.Integer(), nullable=False),
    sa.Column('total_citations', sa.Integer(), nullable=False),
    sa.Column('own_citations', sa.Integer(), nullable=False),
    sa.Column('competitor_citations', sa.Integer(), nullable=False),
    sa.Column('engine_scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_visibility_snapshots_project_id'), 'aeo_visibility_snapshots', ['project_id'], unique=False)
    op.create_table('billing_invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('provider_invoice_id', sa.String(length=128), nullable=True),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('invoice_url', sa.String(length=512), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoices_invoice_number'), 'billing_invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_billing_invoices_provider_invoice_id'), 'billing_invoices', ['provider_invoice_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_subscription_id'), 'billing_invoices', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_user_id'), 'billing_invoices', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_workspace_id'), 'billing_invoices', ['workspace_id'], unique=False)
    op.create_table('geo_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_alerts_project_id'), 'geo_alerts', ['project_id'], unique=False)
    op.create_table('geo_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=False),
    sa.Column('providers', sa.JSON(), nullable=False),
    sa.Column('results_summary', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_analyses_project_id'), 'geo_analyses', ['project_id'], unique=False)
    op.create_table('geo_brand_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('use_cases', sa.JSON(), nullable=False),
    sa.Column('target_users', sa.JSON(), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('pricing_model', sa.String(length=100), nullable=True),
    sa.Column('key_features', sa.JSON(), nullable=False),
    sa.Column('differentiators', sa.JSON(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('social_links', sa.JSON(), nullable=False),
    sa.Column('official_urls', sa.JSON(), nullable=False),
    sa.Column('support_url', sa.String(length=500), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('contact_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_brand_profiles_project_id'), 'geo_brand_profiles', ['project_id'], unique=True)
    op.create_table('geo_change_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('before_value', sa.String(length=255), nullable=True),
    sa.Column('after_value', sa.String(length=255), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_change_events_project_id'), 'geo_change_events', ['project_id'], unique=False)
    op.create_table('geo_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('parent_entity', sa.String(length=255), nullable=True),
    sa.Column('related_entities', sa.JSON(), nullable=False),
    sa.Column('related_topics', sa.JSON(), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('consistency_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_entities_entity_type'), 'geo_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_geo_entities_name'), 'geo_entities', ['name'], unique=False)
    op.create_index(op.f('ix_geo_entities_project_id'), 'geo_entities', ['project_id'], unique=False)
    op.create_table('geo_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('issue_code', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('affected_urls', sa.JSON(), nullable=False),
    sa.Column('affected_questions', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_issues_category'), 'geo_issues', ['category'], unique=False)
    op.create_index(op.f('ix_geo_issues_issue_code'), 'geo_issues', ['issue_code'], unique=False)
    op.create_index(op.f('ix_geo_issues_project_id'), 'geo_issues', ['project_id'], unique=False)
    op.create_table('geo_monitoring_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('providers', sa.JSON(), nullable=False),
    sa.Column('question_limit', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_monitoring_schedules_project_id'), 'geo_monitoring_schedules', ['project_id'], unique=True)
    op.create_table('geo_optimization_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('before_score', sa.Integer(), nullable=True),
    sa.Column('after_score', sa.Integer(), nullable=True),
    sa.Column('before_metric', sa.String(length=100), nullable=True),
    sa.Column('after_metric', sa.String(length=100), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_optimization_history_project_id'), 'geo_optimization_history', ['project_id'], unique=False)
    op.create_table('geo_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity', sa.String(length=255), nullable=True),
    sa.Column('target_product', sa.String(length=255), nullable=True),
    sa.Column('target_service', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=False),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('best_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_questions_category'), 'geo_questions', ['category'], unique=False)
    op.create_index(op.f('ix_geo_questions_project_id'), 'geo_questions', ['project_id'], unique=False)
    op.create_table('geo_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('priority_level', sa.String(length=20), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('how_to_fix', sa.Text(), nullable=False),
    sa.Column('implementation_steps', sa.JSON(), nullable=False),
    sa.Column('affected_prompt_count', sa.Integer(), nullable=False),
    sa.Column('affected_answer_count', sa.Integer(), nullable=False),
    sa.Column('affected_urls', sa.JSON(), nullable=False),
    sa.Column('estimated_impact', sa.Integer(), nullable=False),
    sa.Column('potential_score', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_recommendations_category'), 'geo_recommendations', ['category'], unique=False)
    op.create_index(op.f('ix_geo_recommendations_project_id'), 'geo_recommendations', ['project_id'], unique=False)
    op.create_index(op.f('ix_geo_recommendations_recommendation_code'), 'geo_recommendations', ['recommendation_code'], unique=False)
    op.create_table('geo_visibility_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('mention_rate', sa.Float(), nullable=False),
    sa.Column('recommendation_rate', sa.Float(), nullable=False),
    sa.Column('citation_rate', sa.Float(), nullable=False),
    sa.Column('average_position', sa.Float(), nullable=True),
    sa.Column('share_of_voice', sa.Float(), nullable=False),
    sa.Column('geo_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_visibility_snapshots_project_id'), 'geo_visibility_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_geo_visibility_snapshots_provider'), 'geo_visibility_snapshots', ['provider'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pages_discovered', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('pages_failed', sa.Integer(), nullable=False),
    sa.Column('pages_skipped', sa.Integer(), nullable=False),
    sa.Column('issues_count', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('indexability_score', sa.Integer(), nullable=True),
    sa.Column('metadata_score', sa.Integer(), nullable=True),
    sa.Column('links_score', sa.Integer(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('crawl_duration', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_project_id'), 'scans', ['project_id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('aeo_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=False),
    sa.Column('brand_position', sa.Integer(), nullable=True),
    sa.Column('mention_snippets', sa.JSON(), nullable=False),
    sa.Column('competitor_mentions', sa.JSON(), nullable=False),
    sa.Column('citations_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['aeo_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['aeo_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_answers_analysis_id'), 'aeo_answers', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_aeo_answers_brand_mentioned'), 'aeo_answers', ['brand_mentioned'], unique=False)
    op.create_index(op.f('ix_aeo_answers_engine'), 'aeo_answers', ['engine'], unique=False)
    op.create_index(op.f('ix_aeo_answers_project_id'), 'aeo_answers', ['project_id'], unique=False)
    op.create_index(op.f('ix_aeo_answers_question_id'), 'aeo_answers', ['question_id'], unique=False)
    op.create_table('aeo_change_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('previous_value', sa.String(length=255), nullable=True),
    sa.Column('current_value', sa.String(length=255), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('percentage_delta', sa.Float(), nullable=True),
    sa.Column('related_prompt_id', sa.String(length=36), nullable=True),
    sa.Column('related_competitor', sa.String(length=255), nullable=True),
    sa.Column('related_recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['aeo_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_change_events_analysis_id'), 'aeo_change_events', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_aeo_change_events_event_type'), 'aeo_change_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_aeo_change_events_project_id'), 'aeo_change_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_aeo_change_events_severity'), 'aeo_change_events', ['severity'], unique=False)
    op.create_table('aeo_citations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('citation_type', sa.String(length=50), nullable=False),
    sa.Column('citation_status', sa.String(length=50), nullable=False),
    sa.Column('citation_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['aeo_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_citations_domain'), 'aeo_citations', ['domain'], unique=False)
    op.create_index(op.f('ix_aeo_citations_engine'), 'aeo_citations', ['engine'], unique=False)
    op.create_index(op.f('ix_aeo_citations_project_id'), 'aeo_citations', ['project_id'], unique=False)
    op.create_index(op.f('ix_aeo_citations_question_id'), 'aeo_citations', ['question_id'], unique=False)
    op.create_table('aeo_competitor_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('competitor', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('share_of_voice', sa.Float(), nullable=False),
    sa.Column('average_position', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['aeo_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_competitor_snapshots_analysis_id'), 'aeo_competitor_snapshots', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_aeo_competitor_snapshots_competitor'), 'aeo_competitor_snapshots', ['competitor'], unique=False)
    op.create_index(op.f('ix_aeo_competitor_snapshots_project_id'), 'aeo_competitor_snapshots', ['project_id'], unique=False)
    op.create_table('aeo_engine_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('mention_rate', sa.Float(), nullable=False),
    sa.Column('citation_rate', sa.Float(), nullable=False),
    sa.Column('coverage_rate', sa.Float(), nullable=False),
    sa.Column('average_position', sa.Float(), nullable=True),
    sa.Column('questions_tested', sa.Integer(), nullable=False),
    sa.Column('questions_mentioned', sa.Integer(), nullable=False),
    sa.Column('citations_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['aeo_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_engine_snapshots_analysis_id'), 'aeo_engine_snapshots', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_aeo_engine_snapshots_project_id'), 'aeo_engine_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_aeo_engine_snapshots_provider'), 'aeo_engine_snapshots', ['provider'], unique=False)
    op.create_table('aeo_prompt_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('mentioned', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('citation_found', sa.Boolean(), nullable=False),
    sa.Column('visibility_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['aeo_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['aeo_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_prompt_snapshots_analysis_id'), 'aeo_prompt_snapshots', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_aeo_prompt_snapshots_project_id'), 'aeo_prompt_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_aeo_prompt_snapshots_question_id'), 'aeo_prompt_snapshots', ['question_id'], unique=False)
    op.create_table('geo_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=False),
    sa.Column('brand_mention_type', sa.String(length=50), nullable=False),
    sa.Column('brand_position', sa.Integer(), nullable=True),
    sa.Column('recommendation_position', sa.Integer(), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('recommendation_strength', sa.String(length=50), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('competitor_mentions', sa.JSON(), nullable=False),
    sa.Column('competitor_positions', sa.JSON(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('own_domain_citations', sa.Integer(), nullable=False),
    sa.Column('competitor_citations', sa.Integer(), nullable=False),
    sa.Column('third_party_citations', sa.Integer(), nullable=False),
    sa.Column('raw_citations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['geo_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_answers_project_id'), 'geo_answers', ['project_id'], unique=False)
    op.create_index(op.f('ix_geo_answers_provider'), 'geo_answers', ['provider'], unique=False)
    op.create_index(op.f('ix_geo_answers_question_id'), 'geo_answers', ['question_id'], unique=False)
    op.create_table('optimization_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('previous_scan_id', sa.String(length=36), nullable=True),
    sa.Column('previous_score', sa.Integer(), nullable=True),
    sa.Column('current_score', sa.Integer(), nullable=False),
    sa.Column('score_change', sa.Integer(), nullable=False),
    sa.Column('issues_before', sa.Integer(), nullable=False),
    sa.Column('issues_after', sa.Integer(), nullable=False),
    sa.Column('issues_resolved', sa.Integer(), nullable=False),
    sa.Column('new_issues', sa.Integer(), nullable=False),
    sa.Column('remaining_issues', sa.Integer(), nullable=False),
    sa.Column('pages_improved', sa.Integer(), nullable=False),
    sa.Column('pages_declined', sa.Integer(), nullable=False),
    sa.Column('category_score_changes', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['previous_scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_history_project_id'), 'optimization_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_optimization_history_scan_id'), 'optimization_history', ['scan_id'], unique=False)
    op.create_table('seo_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('final_url', sa.String(length=1024), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.String(length=1024), nullable=True),
    sa.Column('robots_directive', sa.String(length=255), nullable=True),
    sa.Column('x_robots_tag', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('h1_count', sa.Integer(), nullable=False),
    sa.Column('h2_count', sa.Integer(), nullable=False),
    sa.Column('h3_count', sa.Integer(), nullable=False),
    sa.Column('headings', sa.JSON(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('is_indexable', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('crawl_depth', sa.Integer(), nullable=False),
    sa.Column('render_method', sa.String(length=50), nullable=False),
    sa.Column('redirect_chain', sa.JSON(), nullable=False),
    sa.Column('open_graph', sa.JSON(), nullable=False),
    sa.Column('twitter_card', sa.JSON(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_pages_is_indexable'), 'seo_pages', ['is_indexable'], unique=False)
    op.create_index(op.f('ix_seo_pages_scan_id'), 'seo_pages', ['scan_id'], unique=False)
    op.create_index(op.f('ix_seo_pages_status_code'), 'seo_pages', ['status_code'], unique=False)
    op.create_index(op.f('ix_seo_pages_url'), 'seo_pages', ['url'], unique=False)
    op.create_table('aeo_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('change_event_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_event_id'], ['aeo_change_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['aeo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeo_alerts_change_event_id'), 'aeo_alerts', ['change_event_id'], unique=False)
    op.create_index(op.f('ix_aeo_alerts_project_id'), 'aeo_alerts', ['project_id'], unique=False)
    op.create_index(op.f('ix_aeo_alerts_severity'), 'aeo_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_aeo_alerts_status'), 'aeo_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_aeo_alerts_type'), 'aeo_alerts', ['type'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['seo_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_page_id'), 'ai_recommendations', ['page_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_project_id'), 'ai_recommendations', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_recommendation_type'), 'ai_recommendations', ['recommendation_type'], unique=False)
    op.create_table('geo_citations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('answer_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('brand_related', sa.Boolean(), nullable=False),
    sa.Column('competitor_related', sa.Boolean(), nullable=False),
    sa.Column('authority_score', sa.Integer(), nullable=True),
    sa.Column('authority_status', sa.String(length=50), nullable=False),
    sa.Column('citation_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['geo_answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['geo_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_citations_answer_id'), 'geo_citations', ['answer_id'], unique=False)
    op.create_index(op.f('ix_geo_citations_domain'), 'geo_citations', ['domain'], unique=False)
    op.create_index(op.f('ix_geo_citations_project_id'), 'geo_citations', ['project_id'], unique=False)
    op.create_table('seo_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('issue_code', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['seo_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_issues_category'), 'seo_issues', ['category'], unique=False)
    op.create_index(op.f('ix_seo_issues_issue_code'), 'seo_issues', ['issue_code'], unique=False)
    op.create_index(op.f('ix_seo_issues_page_id'), 'seo_issues', ['page_id'], unique=False)
    op.create_index(op.f('ix_seo_issues_scan_id'), 'seo_issues', ['scan_id'], unique=False)
    op.create_index(op.f('ix_seo_issues_severity'), 'seo_issues', ['severity'], unique=False)
    op.create_table('seo_page_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('src', sa.String(length=1024), nullable=False),
    sa.Column('alt', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['seo_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_page_images_page_id'), 'seo_page_images', ['page_id'], unique=False)
    op.create_table('seo_page_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('anchor_text', sa.Text(), nullable=True),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_follow', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['seo_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_page_links_page_id'), 'seo_page_links', ['page_id'], unique=False)
    op.create_index(op.f('ix_seo_page_links_target_url'), 'seo_page_links', ['target_url'], unique=False)
    op.create_table('seo_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=True),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('issue_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('how_to_fix', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('estimated_impact', sa.Float(), nullable=False),
    sa.Column('effort', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('affected_pages_count', sa.Integer(), nullable=False),
    sa.Column('affected_urls', sa.JSON(), nullable=False),
    sa.Column('current_state', sa.Text(), nullable=True),
    sa.Column('recommended_state', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verification_details', sa.JSON(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['seo_issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['seo_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_recommendations_category'), 'seo_recommendations', ['category'], unique=False)
    op.create_index(op.f('ix_seo_recommendations_issue_code'), 'seo_recommendations', ['issue_code'], unique=False)
    op.create_index(op.f('ix_seo_recommendations_issue_id'), 'seo_recommendations', ['issue_id'], unique=False)
    op.create_index(op.f('ix_seo_recommendations_page_id'), 'seo_recommendations', ['page_id'], unique=False)
    op.create_index(op.f('ix_seo_recommendations_priority'), 'seo_recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_seo_recommendations_project_id'), 'seo_recommendations', ['project_id'], unique=False)
    op.create_index(op.f('ix_seo_recommendations_scan_id'), 'seo_recommendations', ['scan_id'], unique=False)
    op.create_index(op.f('ix_seo_recommendations_status'), 'seo_recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_recommendations_status'), table_name='seo_recommendations')
    op.drop_index(op.f('ix_seo_recommendations_scan_id'), table_name='seo_recommendations')
    op.drop_index(op.f('ix_seo_recommendations_project_id'), table_name='seo_recommendations')
    op.drop_index(op.f('ix_seo_recommendations_priority'), table_name='seo_recommendations')
    op.drop_index(op.f('ix_seo_recommendations_page_id'), table_name='seo_recommendations')
    op.drop_index(op.f('ix_seo_recommendations_issue_id'), table_name='seo_recommendations')
    op.drop_index(op.f('ix_seo_recommendations_issue_code'), table_name='seo_recommendations')
    op.drop_index(op.f('ix_seo_recommendations_category'), table_name='seo_recommendations')
    op.drop_table('seo_recommendations')
    op.drop_index(op.f('ix_seo_page_links_target_url'), table_name='seo_page_links')
    op.drop_index(op.f('ix_seo_page_links_page_id'), table_name='seo_page_links')
    op.drop_table('seo_page_links')
    op.drop_index(op.f('ix_seo_page_images_page_id'), table_name='seo_page_images')
    op.drop_table('seo_page_images')
    op.drop_index(op.f('ix_seo_issues_severity'), table_name='seo_issues')
    op.drop_index(op.f('ix_seo_issues_scan_id'), table_name='seo_issues')
    op.drop_index(op.f('ix_seo_issues_page_id'), table_name='seo_issues')
    op.drop_index(op.f('ix_seo_issues_issue_code'), table_name='seo_issues')
    op.drop_index(op.f('ix_seo_issues_category'), table_name='seo_issues')
    op.drop_table('seo_issues')
    op.drop_index(op.f('ix_geo_citations_project_id'), table_name='geo_citations')
    op.drop_index(op.f('ix_geo_citations_domain'), table_name='geo_citations')
    op.drop_index(op.f('ix_geo_citations_answer_id'), table_name='geo_citations')
    op.drop_table('geo_citations')
    op.drop_index(op.f('ix_ai_recommendations_recommendation_type'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_project_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_page_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_aeo_alerts_type'), table_name='aeo_alerts')
    op.drop_index(op.f('ix_aeo_alerts_status'), table_name='aeo_alerts')
    op.drop_index(op.f('ix_aeo_alerts_severity'), table_name='aeo_alerts')
    op.drop_index(op.f('ix_aeo_alerts_project_id'), table_name='aeo_alerts')
    op.drop_index(op.f('ix_aeo_alerts_change_event_id'), table_name='aeo_alerts')
    op.drop_table('aeo_alerts')
    op.drop_index(op.f('ix_seo_pages_url'), table_name='seo_pages')
    op.drop_index(op.f('ix_seo_pages_status_code'), table_name='seo_pages')
    op.drop_index(op.f('ix_seo_pages_scan_id'), table_name='seo_pages')
    op.drop_index(op.f('ix_seo_pages_is_indexable'), table_name='seo_pages')
    op.drop_table('seo_pages')
    op.drop_index(op.f('ix_optimization_history_scan_id'), table_name='optimization_history')
    op.drop_index(op.f('ix_optimization_history_project_id'), table_name='optimization_history')
    op.drop_table('optimization_history')
    op.drop_index(op.f('ix_geo_answers_question_id'), table_name='geo_answers')
    op.drop_index(op.f('ix_geo_answers_provider'), table_name='geo_answers')
    op.drop_index(op.f('ix_geo_answers_project_id'), table_name='geo_answers')
    op.drop_table('geo_answers')
    op.drop_index(op.f('ix_aeo_prompt_snapshots_question_id'), table_name='aeo_prompt_snapshots')
    op.drop_index(op.f('ix_aeo_prompt_snapshots_project_id'), table_name='aeo_prompt_snapshots')
    op.drop_index(op.f('ix_aeo_prompt_snapshots_analysis_id'), table_name='aeo_prompt_snapshots')
    op.drop_table('aeo_prompt_snapshots')
    op.drop_index(op.f('ix_aeo_engine_snapshots_provider'), table_name='aeo_engine_snapshots')
    op.drop_index(op.f('ix_aeo_engine_snapshots_project_id'), table_name='aeo_engine_snapshots')
    op.drop_index(op.f('ix_aeo_engine_snapshots_analysis_id'), table_name='aeo_engine_snapshots')
    op.drop_table('aeo_engine_snapshots')
    op.drop_index(op.f('ix_aeo_competitor_snapshots_project_id'), table_name='aeo_competitor_snapshots')
    op.drop_index(op.f('ix_aeo_competitor_snapshots_competitor'), table_name='aeo_competitor_snapshots')
    op.drop_index(op.f('ix_aeo_competitor_snapshots_analysis_id'), table_name='aeo_competitor_snapshots')
    op.drop_table('aeo_competitor_snapshots')
    op.drop_index(op.f('ix_aeo_citations_question_id'), table_name='aeo_citations')
    op.drop_index(op.f('ix_aeo_citations_project_id'), table_name='aeo_citations')
    op.drop_index(op.f('ix_aeo_citations_engine'), table_name='aeo_citations')
    op.drop_index(op.f('ix_aeo_citations_domain'), table_name='aeo_citations')
    op.drop_table('aeo_citations')
    op.drop_index(op.f('ix_aeo_change_events_severity'), table_name='aeo_change_events')
    op.drop_index(op.f('ix_aeo_change_events_project_id'), table_name='aeo_change_events')
    op.drop_index(op.f('ix_aeo_change_events_event_type'), table_name='aeo_change_events')
    op.drop_index(op.f('ix_aeo_change_events_analysis_id'), table_name='aeo_change_events')
    op.drop_table('aeo_change_events')
    op.drop_index(op.f('ix_aeo_answers_question_id'), table_name='aeo_answers')
    op.drop_index(op.f('ix_aeo_answers_project_id'), table_name='aeo_answers')
    op.drop_index(op.f('ix_aeo_answers_engine'), table_name='aeo_answers')
    op.drop_index(op.f('ix_aeo_answers_brand_mentioned'), table_name='aeo_answers')
    op.drop_index(op.f('ix_aeo_answers_analysis_id'), table_name='aeo_answers')
    op.drop_table('aeo_answers')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_project_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_geo_visibility_snapshots_provider'), table_name='geo_visibility_snapshots')
    op.drop_index(op.f('ix_geo_visibility_snapshots_project_id'), table_name='geo_visibility_snapshots')
    op.drop_table('geo_visibility_snapshots')
    op.drop_index(op.f('ix_geo_recommendations_recommendation_code'), table_name='geo_recommendations')
    op.drop_index(op.f('ix_geo_recommendations_project_id'), table_name='geo_recommendations')
    op.drop_index(op.f('ix_geo_recommendations_category'), table_name='geo_recommendations')
    op.drop_table('geo_recommendations')
    op.drop_index(op.f('ix_geo_questions_project_id'), table_name='geo_questions')
    op.drop_index(op.f('ix_geo_questions_category'), table_name='geo_questions')
    op.drop_table('geo_questions')
    op.drop_index(op.f('ix_geo_optimization_history_project_id'), table_name='geo_optimization_history')
    op.drop_table('geo_optimization_history')
    op.drop_index(op.f('ix_geo_monitoring_schedules_project_id'), table_name='geo_monitoring_schedules')
    op.drop_table('geo_monitoring_schedules')
    op.drop_index(op.f('ix_geo_issues_project_id'), table_name='geo_issues')
    op.drop_index(op.f('ix_geo_issues_issue_code'), table_name='geo_issues')
    op.drop_index(op.f('ix_geo_issues_category'), table_name='geo_issues')
    op.drop_table('geo_issues')
    op.drop_index(op.f('ix_geo_entities_project_id'), table_name='geo_entities')
    op.drop_index(op.f('ix_geo_entities_name'), table_name='geo_entities')
    op.drop_index(op.f('ix_geo_entities_entity_type'), table_name='geo_entities')
    op.drop_table('geo_entities')
    op.drop_index(op.f('ix_geo_change_events_project_id'), table_name='geo_change_events')
    op.drop_table('geo_change_events')
    op.drop_index(op.f('ix_geo_brand_profiles_project_id'), table_name='geo_brand_profiles')
    op.drop_table('geo_brand_profiles')
    op.drop_index(op.f('ix_geo_analyses_project_id'), table_name='geo_analyses')
    op.drop_table('geo_analyses')
    op.drop_index(op.f('ix_geo_alerts_project_id'), table_name='geo_alerts')
    op.drop_table('geo_alerts')
    op.drop_index(op.f('ix_billing_invoices_workspace_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_user_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_subscription_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_provider_invoice_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_invoice_number'), table_name='billing_invoices')
    op.drop_table('billing_invoices')
    op.drop_index(op.f('ix_aeo_visibility_snapshots_project_id'), table_name='aeo_visibility_snapshots')
    op.drop_table('aeo_visibility_snapshots')
    op.drop_index(op.f('ix_aeo_recommendations_recommendation_code'), table_name='aeo_recommendations')
    op.drop_index(op.f('ix_aeo_recommendations_project_id'), table_name='aeo_recommendations')
    op.drop_table('aeo_recommendations')
    op.drop_index(op.f('ix_aeo_questions_question_text'), table_name='aeo_questions')
    op.drop_index(op.f('ix_aeo_questions_project_id'), table_name='aeo_questions')
    op.drop_index(op.f('ix_aeo_questions_category'), table_name='aeo_questions')
    op.drop_table('aeo_questions')
    op.drop_index(op.f('ix_aeo_monitoring_schedules_project_id'), table_name='aeo_monitoring_schedules')
    op.drop_table('aeo_monitoring_schedules')
    op.drop_index(op.f('ix_aeo_entities_project_id'), table_name='aeo_entities')
    op.drop_index(op.f('ix_aeo_entities_entity_name'), table_name='aeo_entities')
    op.drop_table('aeo_entities')
    op.drop_index(op.f('ix_aeo_analyses_status'), table_name='aeo_analyses')
    op.drop_index(op.f('ix_aeo_analyses_project_id'), table_name='aeo_analyses')
    op.drop_table('aeo_analyses')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_domain'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_geo_projects_user_id'), table_name='geo_projects')
    op.drop_index(op.f('ix_geo_projects_domain'), table_name='geo_projects')
    op.drop_table('geo_projects')
    op.drop_index(op.f('ix_billing_usage_events_workspace_id'), table_name='billing_usage_events')
    op.drop_index(op.f('ix_billing_usage_events_user_id'), table_name='billing_usage_events')
    op.drop_index(op.f('ix_billing_usage_events_module'), table_name='billing_usage_events')
    op.drop_table('billing_usage_events')
    op.drop_index(op.f('ix_billing_subscriptions_workspace_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_user_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider_subscription_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider_customer_id'), table_name='billing_subscriptions')
    op.drop_table('billing_subscriptions')
    op.drop_index(op.f('ix_billing_payments_workspace_id'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_user_id'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_provider_payment_id'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_provider_checkout_session_id'), table_name='billing_payments')
    op.drop_table('billing_payments')
    op.drop_index(op.f('ix_billing_customers_workspace_id'), table_name='billing_customers')
    op.drop_index(op.f('ix_billing_customers_user_id'), table_name='billing_customers')
    op.drop_index(op.f('ix_billing_customers_provider_customer_id'), table_name='billing_customers')
    op.drop_table('billing_customers')
    op.drop_index(op.f('ix_billing_credit_wallets_workspace_id'), table_name='billing_credit_wallets')
    op.drop_index(op.f('ix_billing_credit_wallets_user_id'), table_name='billing_credit_wallets')
    op.drop_table('billing_credit_wallets')
    op.drop_index(op.f('ix_billing_credit_transactions_workspace_id'), table_name='billing_credit_transactions')
    op.drop_index(op.f('ix_billing_credit_transactions_user_id'), table_name='billing_credit_transactions')
    op.drop_index(op.f('ix_billing_credit_transactions_type'), table_name='billing_credit_transactions')
    op.drop_index(op.f('ix_billing_credit_transactions_idempotency_key'), table_name='billing_credit_transactions')
    op.drop_table('billing_credit_transactions')
    op.drop_index(op.f('ix_billing_credit_purchases_workspace_id'), table_name='billing_credit_purchases')
    op.drop_index(op.f('ix_billing_credit_purchases_user_id'), table_name='billing_credit_purchases')
    op.drop_index(op.f('ix_billing_credit_purchases_provider_payment_id'), table_name='billing_credit_purchases')
    op.drop_table('billing_credit_purchases')
    op.drop_index(op.f('ix_aeo_projects_user_id'), table_name='aeo_projects')
    op.drop_index(op.f('ix_aeo_projects_domain'), table_name='aeo_projects')
    op.drop_table('aeo_projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_platform_integrations_provider'), table_name='platform_integrations')
    op.drop_table('platform_integrations')
    op.drop_index(op.f('ix_password_resets_email'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_billing_webhook_events_event_type'), table_name='billing_webhook_events')
    op.drop_index(op.f('ix_billing_webhook_events_event_id'), table_name='billing_webhook_events')
    op.drop_table('billing_webhook_events')
    op.drop_index(op.f('ix_billing_plans_code'), table_name='billing_plans')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###
