from typing import Any, Dict, Optional
from app.models.seo_recommendation import RecommendationEffort, RecommendationPriority


RECOMMENDATION_RULE_CATALOG: Dict[str, Dict[str, Any]] = {
    # --- Technical & Indexability ---
    "missing_canonical": {
        "title": "Add self-referential canonical tags to affected pages",
        "description": "Pages without canonical tags risk duplicate content penalties across protocol, subdomain, and query-parameter variations.",
        "why_it_matters": "A canonical tag tells search engines which version of a URL represents the master copy, consolidating ranking signals and preventing indexing fragmentation.",
        "how_to_fix": "Add a <link rel=\"canonical\" href=\"https://example.com/target-page\" /> tag inside the <head> section of each affected page pointing to its preferred permanent URL.",
        "category": "technical",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.CRITICAL.value,
        "base_impact": 4.5,
        "current_state_template": "Missing <link rel=\"canonical\"> tag in HTML <head>",
        "recommended_state_template": "<link rel=\"canonical\" href=\"{canonical_url}\" />",
    },
    "canonical_mismatch": {
        "title": "Resolve conflicting or mismatched canonical URL declarations",
        "description": "The declared canonical tag points to a different URL or uses mismatched protocol/trailing slashes.",
        "why_it_matters": "Mismatched canonicals confuse search engine indexers and may result in Google ignoring canonical declarations entirely.",
        "how_to_fix": "Verify that the href attribute matches the intended canonical URL format exactly, including protocol (https://) and trailing slash.",
        "category": "technical",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.HIGH.value,
        "base_impact": 3.2,
        "current_state_template": "Canonical points to divergent URL: {current_value}",
        "recommended_state_template": "Canonical self-references target page: {canonical_url}",
    },
    "http_error_4xx": {
        "title": "Fix broken 4xx client error pages and repair incoming links",
        "description": "Pages returning 404/403/410 status codes disrupt user experience and waste search engine crawl budget.",
        "why_it_matters": "404 Not Found errors cause visitors to bounce immediately and prevent search crawlers from discovering downstream links.",
        "how_to_fix": "Restore deleted content, redirect dead URLs to relevant live pages using 301 permanent redirects, or update internal links pointing to them.",
        "category": "technical",
        "effort": RecommendationEffort.MEDIUM.value,
        "base_priority": RecommendationPriority.CRITICAL.value,
        "base_impact": 5.0,
        "current_state_template": "Server returned HTTP 404 / 4xx Not Found",
        "recommended_state_template": "HTTP 200 OK or 301 Permanent Redirect to relevant active page",
    },
    "http_error_5xx": {
        "title": "Resolve server 5xx errors to prevent crawl termination",
        "description": "Pages returning 500/502/503 errors represent critical server failures preventing crawl and indexing.",
        "why_it_matters": "Search engines quickly de-index URLs that consistently return 5xx errors to avoid sending users to broken endpoints.",
        "how_to_fix": "Inspect backend server error logs, database timeouts, or edge gateway timeouts causing 5xx server exceptions.",
        "category": "technical",
        "effort": RecommendationEffort.HIGH.value,
        "base_priority": RecommendationPriority.CRITICAL.value,
        "base_impact": 6.5,
        "current_state_template": "Server returned HTTP 500 / 5xx Server Error",
        "recommended_state_template": "Server resolves with HTTP 200 OK and TTFB < 500ms",
    },
    "noindex_directive": {
        "title": "Review noindex meta robots tags on valuable content pages",
        "description": "Pages contain 'noindex' directives in meta robots or X-Robots-Tag headers.",
        "why_it_matters": "The noindex directive instructs search engines not to include the page in search result indexes.",
        "how_to_fix": "If this page was intended to rank in organic search, remove 'noindex' from the <meta name=\"robots\"> tag or HTTP response headers.",
        "category": "indexability",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.CRITICAL.value,
        "base_impact": 6.0,
        "current_state_template": "<meta name=\"robots\" content=\"noindex, follow\">",
        "recommended_state_template": "<meta name=\"robots\" content=\"index, follow\">",
    },
    "disallowed_by_robots": {
        "title": "Unblock important landing pages in robots.txt",
        "description": "Key page paths match Disallow directives in the website's robots.txt file.",
        "why_it_matters": "Search engine bots cannot crawl blocked pages to evaluate on-page content, internal links, or structured data.",
        "how_to_fix": "Edit robots.txt to remove Disallow rules covering public pages meant for search indexing.",
        "category": "indexability",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.HIGH.value,
        "base_impact": 4.0,
        "current_state_template": "Disallow rule active in robots.txt for path",
        "recommended_state_template": "Allow rule or unconstrained path in robots.txt",
    },
    "slow_ttfb": {
        "title": "Optimize server response time and Time to First Byte (TTFB)",
        "description": "Server response time exceeded 2.0 seconds during crawl, impacting Core Web Vitals.",
        "why_it_matters": "Fast TTFB is essential for search crawlers to crawl more pages efficiently and improves user engagement metrics.",
        "how_to_fix": "Enable page caching, optimize database queries, implement a CDN (Cloudflare/Fastly), and upgrade server compute resources.",
        "category": "technical",
        "effort": RecommendationEffort.HIGH.value,
        "base_priority": RecommendationPriority.HIGH.value,
        "base_impact": 2.8,
        "current_state_template": "Response Time: > 2000ms",
        "recommended_state_template": "Response Time: < 600ms (Target: < 200ms)",
    },
    "deep_crawl_depth": {
        "title": "Flatten crawl depth architecture for deeply nested pages",
        "description": "Pages located at crawl depth > 3 from the homepage receive reduced PageRank and crawl frequency.",
        "why_it_matters": "Search bots prioritize shallow pages in the site architecture. Deep pages often suffer from lower indexing rates.",
        "how_to_fix": "Add internal links from higher-level category pages, footer menus, or featured hub modules to reduce click depth to <= 3.",
        "category": "technical",
        "effort": RecommendationEffort.MEDIUM.value,
        "base_priority": RecommendationPriority.MEDIUM.value,
        "base_impact": 1.8,
        "current_state_template": "Crawl Depth: Level 4 or deeper",
        "recommended_state_template": "Crawl Depth: Level 2 or 3 from Homepage",
    },

    # --- Metadata & Headings ---
    "missing_title": {
        "title": "Add descriptive <title> tags to all pages",
        "description": "Pages are missing a <title> element inside the HTML <head>.",
        "why_it_matters": "Title tags are one of the most critical on-page ranking factors and serve as the primary clickable headline in SERPs.",
        "how_to_fix": "Add a unique title tag between 50–60 characters that incorporates primary keywords and your brand name.",
        "category": "metadata",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.CRITICAL.value,
        "base_impact": 5.5,
        "current_state_template": "<title> missing in <head>",
        "recommended_state_template": "<title>Primary Topic | Brand Name</title> (50-60 chars)",
    },
    "title_too_short": {
        "title": "Expand short title tags to maximize keyword relevance",
        "description": "Title tags with fewer than 30 characters underutilize valuable search snippet space.",
        "why_it_matters": "Short titles lack descriptive context and miss opportunities to capture relevant long-tail search intent.",
        "how_to_fix": "Expand title length to 50–60 characters by adding specific product benefits, categories, or brand identifiers.",
        "category": "metadata",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.MEDIUM.value,
        "base_impact": 1.5,
        "current_state_template": "Title length: < 30 characters",
        "recommended_state_template": "Title length: 50–60 characters with primary intent keyword",
    },
    "title_too_long": {
        "title": "Shorten title tags to prevent SERP truncation",
        "description": "Titles exceeding 60 characters or ~600px pixel width will be truncated with an ellipsis (...) in Google search results.",
        "why_it_matters": "Truncated titles look unprofessional, hide important keywords, and reduce organic click-through rates.",
        "how_to_fix": "Front-load primary keywords and condense title text to 50–60 characters.",
        "category": "metadata",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.LOW.value,
        "base_impact": 0.8,
        "current_state_template": "Title length: > 60 characters (truncated in SERP)",
        "recommended_state_template": "Title length: 50–60 characters",
    },
    "missing_meta_description": {
        "title": "Generate unique meta descriptions for affected pages",
        "description": "Pages lack a <meta name=\"description\"> tag, causing search engines to pull arbitrary body text for snippets.",
        "why_it_matters": "A compelling meta description increases organic CTR and provides users with a clear value proposition before clicking.",
        "how_to_fix": "Craft a unique 120–160 character description that accurately summarizes page benefits and includes a clear call to action.",
        "category": "metadata",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.HIGH.value,
        "base_impact": 3.1,
        "current_state_template": "<meta name=\"description\"> missing",
        "recommended_state_template": "<meta name=\"description\" content=\"Clear 120-160 char summary with compelling CTA\">",
    },
    "meta_description_too_short": {
        "title": "Expand short meta descriptions with compelling context",
        "description": "Meta descriptions under 70 characters fail to provide sufficient context in search results.",
        "why_it_matters": "Short snippets take up less visual space in search listings and achieve lower click-through rates.",
        "how_to_fix": "Expand the description to 120–160 characters by adding key features, benefits, and an action-oriented closing.",
        "category": "metadata",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.MEDIUM.value,
        "base_impact": 1.2,
        "current_state_template": "Meta description: < 70 characters",
        "recommended_state_template": "Meta description: 120–160 characters",
    },
    "meta_description_too_long": {
        "title": "Trim over-length meta descriptions to prevent clipping",
        "description": "Meta descriptions exceeding 160 characters are clipped with an ellipsis in desktop and mobile SERPs.",
        "why_it_matters": "Clipped descriptions may lose critical call-to-actions placed at the end of the sentence.",
        "how_to_fix": "Condense message to under 160 characters while retaining primary value proposition and keywords.",
        "category": "metadata",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.LOW.value,
        "base_impact": 0.6,
        "current_state_template": "Meta description: > 160 characters",
        "recommended_state_template": "Meta description: 120–160 characters",
    },
    "missing_h1": {
        "title": "Add a single primary <h1> heading to each page",
        "description": "Pages lack a main <h1> heading to establish topical hierarchy.",
        "why_it_matters": "The H1 tag is a primary structural signal helping search engines and accessibility screen readers understand the main page topic.",
        "how_to_fix": "Add exactly one descriptive <h1> tag near the top of the main body content matching the core page intent.",
        "category": "content",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.HIGH.value,
        "base_impact": 2.5,
        "current_state_template": "No <h1> heading found on page",
        "recommended_state_template": "<h1>Clear, descriptive primary page headline</h1>",
    },
    "multiple_h1": {
        "title": "Consolidate multiple <h1> tags into a structured heading hierarchy",
        "description": "Pages contain more than one <h1> heading tag, diluting topical clarity.",
        "why_it_matters": "Best practice is to maintain a single H1 representing the page title, using H2 and H3 for sub-sections.",
        "how_to_fix": "Keep the main page headline as <h1> and convert secondary headings to <h2> or <h3> tags.",
        "category": "content",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.LOW.value,
        "base_impact": 0.8,
        "current_state_template": "Multiple (2+) <h1> tags present",
        "recommended_state_template": "Single <h1> headline with structured <h2>/<h3> subsections",
    },

    # --- Content Quality ---
    "thin_content": {
        "title": "Expand thin content pages with comprehensive topical substance",
        "description": "Pages contain fewer than 200 words of substantive text content.",
        "why_it_matters": "Search engines prioritize comprehensive, helpful content. Thin pages are vulnerable to low quality filters.",
        "how_to_fix": "Add detailed explanations, user guides, FAQs, comparison tables, and customer value propositions to exceed 500+ words.",
        "category": "content",
        "effort": RecommendationEffort.HIGH.value,
        "base_priority": RecommendationPriority.HIGH.value,
        "base_impact": 3.5,
        "current_state_template": "Word count: < 200 words (thin content risk)",
        "recommended_state_template": "Word count: 500+ words with structured topical sections",
    },
    "empty_content": {
        "title": "Populate empty content pages or consolidate with parent topics",
        "description": "Pages return negligible text content (< 50 words) despite returning HTTP 200.",
        "why_it_matters": "Empty pages waste crawl budget, provide zero user value, and harm site-wide quality evaluations.",
        "how_to_fix": "Add complete content or set up a 301 redirect to merge this URL with its parent category.",
        "category": "content",
        "effort": RecommendationEffort.HIGH.value,
        "base_priority": RecommendationPriority.HIGH.value,
        "base_impact": 4.0,
        "current_state_template": "Word count: < 50 words (empty page)",
        "recommended_state_template": "Substantive content or 301 redirect to relevant page",
    },

    # --- Links & Images ---
    "missing_image_alt": {
        "title": "Add descriptive alt attributes to image tags",
        "description": "Images on the page are missing the 'alt' text attribute.",
        "why_it_matters": "Alt text enables visual search indexing (Google Images), improves accessibility for visually impaired users, and reinforces keyword context.",
        "how_to_fix": "Add descriptive, concise alt attributes (e.g. alt=\"SeoSensing SEO audit dashboard overview\") to all informational images.",
        "category": "content",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.MEDIUM.value,
        "base_impact": 1.4,
        "current_state_template": "<img src=\"...\" /> (missing alt attribute)",
        "recommended_state_template": "<img src=\"...\" alt=\"Descriptive image context\" />",
    },
    "broken_internal_links": {
        "title": "Fix broken internal links pointing to non-existent URLs",
        "description": "Internal links on the website point to broken (404/500) destinations.",
        "why_it_matters": "Broken links trap search engine crawlers, leak PageRank equity, and frustrate visitors attempting to navigate.",
        "how_to_fix": "Update anchor href URLs to point to valid active pages or remove outdated links.",
        "category": "links",
        "effort": RecommendationEffort.MEDIUM.value,
        "base_priority": RecommendationPriority.HIGH.value,
        "base_impact": 3.8,
        "current_state_template": "Internal links point to 404/broken targets",
        "recommended_state_template": "All internal links resolve with HTTP 200 OK",
    },
    "broken_external_links": {
        "title": "Repair or update broken outbound external links",
        "description": "Outbound external links return error codes (404/500).",
        "why_it_matters": "Outbound link hygiene signals content freshness and credibility to search engines.",
        "how_to_fix": "Replace broken external reference links with updated authoritative sources or remove dead citations.",
        "category": "links",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.LOW.value,
        "base_impact": 0.9,
        "current_state_template": "External link points to dead domain/404 URL",
        "recommended_state_template": "External links point to valid authoritative sources",
    },

    # --- Social & Structured Data ---
    "missing_og_title": {
        "title": "Implement Open Graph metadata for rich social snippet sharing",
        "description": "Pages are missing Open Graph tags (og:title, og:description, og:image).",
        "why_it_matters": "Open Graph tags optimize appearance when links are shared on LinkedIn, X, Slack, and Facebook, increasing referral traffic.",
        "how_to_fix": "Add <meta property=\"og:title\">, <meta property=\"og:description\">, and <meta property=\"og:image\"> in the HTML <head>.",
        "category": "metadata",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.LOW.value,
        "base_impact": 0.7,
        "current_state_template": "Missing og:title / og:image tags in <head>",
        "recommended_state_template": "<meta property=\"og:title\" content=\"...\"> with preview image",
    },
    "missing_twitter_card": {
        "title": "Add Twitter Card meta tags for enhanced card previews",
        "description": "Pages lack twitter:card and twitter:title meta elements.",
        "why_it_matters": "Twitter Card tags ensure rich summary visual cards render when links are shared on social platforms.",
        "how_to_fix": "Add <meta name=\"twitter:card\" content=\"summary_large_image\"> to the <head>.",
        "category": "metadata",
        "effort": RecommendationEffort.LOW.value,
        "base_priority": RecommendationPriority.LOW.value,
        "base_impact": 0.5,
        "current_state_template": "Missing twitter:card meta tags",
        "recommended_state_template": "<meta name=\"twitter:card\" content=\"summary_large_image\">",
    },
}


def get_rule_for_issue_code(issue_code: str) -> Dict[str, Any]:
    """Retrieve rule definition or generate deterministic fallback."""
    if issue_code in RECOMMENDATION_RULE_CATALOG:
        return RECOMMENDATION_RULE_CATALOG[issue_code]

    # Clean formatting for novel issue codes
    cleaned_title = issue_code.replace("_", " ").title()
    return {
        "title": f"Resolve {cleaned_title} issue",
        "description": f"Audit detected '{issue_code}' affecting pages in this project.",
        "why_it_matters": "Resolving this issue improves overall site health, crawlability, and search performance.",
        "how_to_fix": "Inspect the affected URLs and apply the recommended technical corrections.",
        "category": "technical",
        "effort": RecommendationEffort.MEDIUM.value,
        "base_priority": RecommendationPriority.MEDIUM.value,
        "base_impact": 1.0,
        "current_state_template": f"Detected issue: {issue_code}",
        "recommended_state_template": f"Resolved: {issue_code}",
    }
